// Master registry of all topics across all note pages
const notesCatalog = [
  {
    title: "Average Power",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=7",
    keywords: [],
  },
  {
    title: "ADC - ADS1115",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Arduino",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=74",
    keywords: [],
  },
  {
    title: "Beam Quality",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=8",
    keywords: [],
  },
  {
    title: "Beam Properties",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=12",
    keywords: [],
  },
  {
    title: "Beam Collimation Check",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=20",
    keywords: [],
  },
  {
    title: "Beam Hardening",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=58",
    keywords: [],
  },
  {
    title: "Beam Line",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=79",
    keywords: [],
  },
  {
    title: "Butter Paper",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=81",
    keywords: [],
  },
  {
    title: "Bellows",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=85",
    keywords: [],
  },
  {
    title: "CW-Pulsed Lasers",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=1",
    keywords: [],
  },
  {
    title: "Coherence - Measurement and Studies",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=19",
    keywords: [],
  },
  {
    title: "CXRO Database",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=38",
    keywords: [],
  },
  {
    title: "Convergence Graphs",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=51",
    keywords: [],
  },
  {
    title: "Current Phase",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=53",
    keywords: [],
  },
  {
    title: "Clean Rooms",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=55",
    keywords: [],
  },
  {
    title: "Compressor",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=86",
    keywords: [],
  },
  {
    title: "CPA",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=87",
    keywords: [],
  },
  {
    title: "Dual Op-Amp - LM358N",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Diffraction Limit",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=44",
    keywords: [],
  },
  {
    title: "Detectors",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=49",
    keywords: [],
  },
  {
    title: "Discrepancy Principle",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=52",
    keywords: [],
  },
  {
    title: "Dipole",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=61",
    keywords: [],
  },
  {
    title: "Electron Temp and Significance",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=62",
    keywords: [],
  },
  {
    title: "Electron Spectrometer",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=26",
    keywords: [],
  },
  {
    title: "Electron Beam Optimization",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=34",
    keywords: [],
  },
  {
    title: "Electric Motors",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=67",
    keywords: [],
  },
  {
    title: "ESP32",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=75",
    keywords: [],
  },
  {
    title: "Filters",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=37",
    keywords: [],
  },
  {
    title: "Farfield Imaging",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=43",
    keywords: [],
  },
  {
    title: "Faraday's Law of Induction",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=68",
    keywords: [],
  },
  {
    title: "Fabry-Pèrot Cavity - Interferometer and Applications",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=71",
    keywords: [],
  },
  {
    title: "Flanges",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=85",
    keywords: [],
  },
  {
    title: "Gimbal Mounts",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=82",
    keywords: [],
  },
  {
    title: "Gauge Controller",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=89",
    keywords: [],
  },
  {
    title: "Harmonics - Low Order Harmonics, HHG",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=22",
    keywords: [],
  },
  {
    title: "Hall Probe",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Intensity",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=9",
    keywords: [],
  },
  {
    title: "Interference",
    page: "June-July",
    url: "Jun_Jul/jun_jul.html?id=92",
    keywords: [],
  },
  {
    title: "Jitters",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=54",
    keywords: [],
  },
  {
    title: "K-Potentiometer",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "K-edge",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=37",
    keywords: [],
  },
  {
    title: "Lanex",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=27",
    keywords: [],
  },
  {
    title: "Limit Switches",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Mode Locking",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=3",
    keywords: [],
  },
  {
    title: "MOSFET - IRF540",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Microcontrollers",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=73",
    keywords: [],
  },
  {
    title: "Nonlinearity",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=15",
    keywords: [],
  },
  {
    title: "Oscilloscope",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=70",
    keywords: [],
  },
  {
    title: "Pulse Laser",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=1",
    keywords: [],
  },
  {
    title: "Pulse Energy",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=5",
    keywords: [],
  },
  {
    title: "Pulse Peak Power",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=6",
    keywords: [],
  },
  {
    title: "Pulse Duration Measurement",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=10",
    keywords: [],
  },
  {
    title: "Profiles",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=11",
    keywords: [],
  },
  {
    title: "Plasmons",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=16",
    keywords: [],
  },
  {
    title: "Pre-Pulse and Pedestal",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=25",
    keywords: [],
  },
  {
    title: "Poisson Statistics",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=60",
    keywords: [],
  },
  {
    title: "Plasma Density",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=64",
    keywords: [],
  },
  {
    title: "Plasma Length",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=66",
    keywords: [],
  },
  {
    title: "Plasma Gradient",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=65",
    keywords: [],
  },
  {
    title: "PID Error Correction",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=69",
    keywords: [],
  },
  {
    title: "Polarimeter",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=88",
    keywords: [],
  },
  {
    title: "Perspex",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=91",
    keywords: [],
  },
  {
    title: "Q-Switching",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=2",
    keywords: [],
  },
  {
    title: "Regulator - 7805",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Ross Pairs",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=39",
    keywords: [],
  },
  {
    title: "R2D2 Chamber",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=84",
    keywords: [],
  },
  {
    title: "Synchronous Beam",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=13",
    keywords: [],
  },
  {
    title: "Stepper Motor",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Stepper Motor Driver - A4988",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=28",
    keywords: [],
  },
  {
    title: "Spectral Unfolding",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=41",
    keywords: [],
  },
  {
    title: "Spectral Reconstruction",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=59",
    keywords: [],
  },
  {
    title: "TPD",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=16",
    keywords: [],
  },
  {
    title: "Transition Edge Sensor",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=36",
    keywords: [],
  },
  {
    title: "Thermal Lensing",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=76",
    keywords: [],
  },
  {
    title: "Turbo Molecular Pump",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=83",
    keywords: [],
  },
  {
    title: "Vacuum",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=78",
    keywords: [],
  },
  {
    title: "Wavefront",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=21",
    keywords: [],
  },
  {
    title: "Wakefield Injection",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=77",
    keywords: [],
  },
  {
    title: "X-Ray HSI",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=33",
    keywords: [],
  },
  {
    title: "X-Ray Broadband Spectrum Separation",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=35",
    keywords: [],
  },
  {
    title: "X-Ray Spectrum Diagnosis",
    page: "June - July",
    url: "Jun_Jul/jun_jul.html?id=50",
    keywords: [],
  },
  // Aug-Sep
  {
    title: "Allied vision camera",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=10",
    keywords: [],
  },
  {
    title: "Beam shaft coupler - ESM comp",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=6",
    keywords: [],
  },
  {
    title: "Beam splitters",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=4",
    keywords: [],
  },
  {
    title: "Bearing blocks(flanges, ball, pillow) - ESM comp",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=6",
    keywords: [],
  },
  {
    title: "Coherent Astrella",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=8",
    keywords: [],
  },
  {
    title: "Collar",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=6",
    keywords: [],
  },
  {
    title: "Dichroic mirrors",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=4",
    keywords: [],
  },
  {
    title: "Dielectric mirrors",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=3",
    keywords: [],
  },
  {
    title: "Diffraction gratings",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=5",
    keywords: [],
  },
  {
    title: "EM waves - principles and equations",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=19",
    keywords: [],
  },
  {
    title: "Feedthroughs",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=1",
    keywords: [],
  },
  {
    title: "Ferrule",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=1",
    keywords: [],
  },
  {
    title: "Fleming's left hand rule",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=17",
    keywords: [],
  },
  {
    title: "Hex screws",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=7",
    keywords: [],
  },
  {
    title: "Kerr effect",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=21",
    keywords: [],
  },
  {
    title: "Laser DOF",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=15",
    keywords: [],
  },
  {
    title: "Lead screw - ESM comp",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=6",
    keywords: [],
  },
  {
    title: "Lorentz force",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=16",
    keywords: [],
  },
  {
    title: "OAP",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=2",
    keywords: [],
  },
  {
    title: "Optics",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=1",
    keywords: [],
  },
  {
    title: "Pb uses in labs against radiation",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=14",
    keywords: [],
  },
  {
    title: "Pirani gauge",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=1",
    keywords: [],
  },
  {
    title: "Plasma density",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=26",
    keywords: [],
  },
  {
    title: "PoE ethernet switch",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=11",
    keywords: [],
  },
  {
    title: "Polyethylene sheets",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=12",
    keywords: [],
  },
  {
    title: "Ponderomotive force",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=23",
    keywords: [],
  },
  {
    title: "Potentials - scalar electric potential, magnetic vector potential",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=20",
    keywords: [],
  },
  {
    title: "PTFE flexible pipes",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=13",
    keywords: [],
  },
  {
    title: "Pump beams for oscillator/amplifiers",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=9",
    keywords: [],
  },
  {
    title: "Relativistic physics",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=18",
    keywords: [],
  },
  {
    title: "Self-focusing",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=22",
    keywords: [],
  },
  {
    title: "Vector calculus operators",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=24",
    keywords: [],
  },
  {
    title: "Vimba",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=10",
    keywords: [],
  },
  {
    title: "Liquid Targets in LPI",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=27",
    keywords: [],
  },
  {
    title: "Optical Masks",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=28",
    keywords: [],
  },
  {
    title: "Beam Splitters",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=29",
    keywords: [],
  },
  {
    title: "Mask vs BS",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=30",
    keywords: [],
  },
  {
    title: "Delay, Delay Lines",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=31",
    keywords: [],
  },
  {
    title: "Michelson vs Mach-Zehnder",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=32",
    keywords: [],
  },
  {
    title: "Superluminal Phase Velocity",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=33",
    keywords: [],
  },
  {
    title: "Sub-cycle Timescale",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=34",
    keywords: [],
  },
  {
    title: "Relativistic Oscillating Mirror(ROM) Mechanism",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=35",
    keywords: [],
  },
  {
    title: "Phased Array Effect",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=36",
    keywords: [],
  },
  {
    title: "Carrier Phase Envelope - CEP",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=37",
    keywords: [],
  },
  {
    title: "Collinear, Noncollinear Beams, Recombination",
    page: "August - September",
    url: "Aug_Sep/aug_sep.html?id=38",
    keywords: ["collinear", "noncollinear", "recombination"],
  },
  //October-November
  {
    title: "Field Description - Eulerian, Lagranginan, Hamiltonian",
    page: "Ovtober - November",
    url: "Oct_Nov/oct_nov.html?id=1",
    keywords: [],
  },
  {
    title: "Phase Space",
    page: "Ovtober - November",
    url: "Oct_Nov/oct_nov.html?id=2",
    keywords: [],
  },
  {
    title: "Frame of Reference",
    page: "Ovtober - November",
    url: "Oct_Nov/oct_nov.html?id=3",
    keywords: [],
  },
  {
    title: "Fourier Optics",
    page: "Ovtober - November",
    url: "Oct_Nov/oct_nov.html?id=4",
    keywords: [],
  },
];
